server:
  port: 9087
spring:
  rabbitmq:
    host: 39.104.169.209
    port: 5672
    username: admin
    password: admin
    virtual-host: /
    connection-timeout: 10000
    listener:
      simple:
        acknowledge-mode: manual # 手动应答
        auto-startup: true
        default-requeue-rejected: false # 不重回队列
        concurrency: 5
        max-concurrency: 20
        prefetch: 1 # 每次只处理一个信息
        retry:
          enabled: false
